# [Link to video.](https://www.youtube.com/watch?v=nZmbNHTqEss&list=PLVD25niNi0BkMe4nxXTL4vFED06M6ccpg)

### Raising Errors

We've seen a variety of error messages that appear when our programs end abruptly. We can create our own errors messages too.

```python
def multiply(*nums):
    """Takes an unlimited number of integers and multiplies them."""
    try:
        result = 1
        for num in nums:
            result *= num
        return result
    except:
        raise TypeError("All arguments must be integers")

print(multiply(3, -4, 2, 7))  # prints -168
print(multiple("hi"))  # prints an error message saying "TypeError: All arguments must be integers"
```

The keyword `raise` is used to raise an error. We can use any of the [built-in errors](https://docs.python.org/3/library/exceptions.html).

If we `raise` within an `except` block, we'll get both the original error as well as the new error. We can avoid getting the first one by using a boolean variable to keep track of whether we need to raise it

```python
def multiply(*nums):
    """Takes an unlimited number of integers and multiplies them."""
    error = False
    try:
        result = 1
        for num in nums:
            result *= num
        return result
    except:
        error = True
    if error:
        raise TypeError("All arguments must be integers")

print(add_integers("hi"))  # prints an error message saying "TypeError: All arguments must be integers."
```  

We can also create our own custom error types, which we'll do later this unit.
